# This is a basic workflow to help you get started with Actions

name: workflow1
on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "choose an environment"
        required: true
        type: choice
        default: 'dev'
        options:
        - dev
        - test
        - prod
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:      

  build:
    env:
      services: '{"service1": [ "dockerfile": "somepath to dockerfile for service 1", "servicename": "MyServiceOne" ] }'
      
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.target_environment }}
    steps:
      - name: check-prereqs
        run: |
          if [ -z "${{ vars.ENV_ONE }}" ]; then
            echo "ENV_ONE is not set in environments settings"
            exit 1
          fi

      - name: checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Got this environment - '${{ inputs.target_environment }}', with this ENV_ONE value ${{ vars.ENV_ONE }}, and this SECRET_ONE value ${{ secrets.SECRET_ONE }}"

      - name: interrogate service array
        run: echo "Service1.dockerfile is ${{ env.services.service1.dockerfile }}"
