# This is a basic workflow to help you get started with Actions

name: workflow1
on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "choose an environment"
        required: true
        type: choice
        default: 'dev'
        options:
        - dev
        - test
        - prod
        
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.target_environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Got this environment - '${{ inputs.target_environment }}', with this ENV_ONE value ${{ vars.ENV_ONE }}, and this SECRET_ONE value ${{ secrets.SECRET_ONE }}"
